### ISSUE TITLE
tex convert-all

### ISSUE THREAD

**Issue by Fabiosek** [vs49688/CrocUtils#4]
Hi. 
Is it also possible to decompile massively textures from .pix to png? (like wad extract-all). Single (8,000 textures) will be time consuming.

**Comment by vs49688** [comment]
It's possible, but a simple bash one-liner would be easier:
```
for i in *; do croctool tex convert "$i"; done
```
Unless you're on Windows, I'm not sure how to do loops in Batch or PowerShell.

**Comment by Fabiosek** [comment]
I only use Windows 10 PRO and CMD.

**Comment by vs49688** [comment]
I don't have time to work on this currently, please see https://ss64.com/nt/for.html. But I will leave this open as a feature request.

**Comment by vs49688** [comment]
So, I've had a think about this - most textures can be converted normally, however some require colour-keying. However, this isn't stored in the texture, so there's no way to determine which.

I'm going to close this as I can't see a feasible way to do it with the textures alone. I'll revisit this after I (eventually) implement material handling.
